<?xml version="1.0" ?>
<robot name="rover_amalia_chassis" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="pi" value="3.1415926"/>

  <xacro:property name="rover_amalia_chassis_turret_base_pose">
     <pose>0.195 0 0.073 0 -0 0</pose>
  </xacro:property>
  <xacro:property name="rover_amalia_chassis_turret_base_size">
     <size>0.089 0.064 0.046</size>
  </xacro:property>
  <xacro:property name="rover_amalia_chassis_body_size">
     <size>0.492 0.334 0.1</size>
  </xacro:property>

  <xacro:property name="rover_amalia_chassis_rangefinder_size_y" value="0.01"/>
  <xacro:property name="rover_amalia_chassis_rangefinder_size">
    <size>${rover_amalia_chassis_rangefinder_size_y} 0.03 ${rover_amalia_chassis_rangefinder_size_y}</size>
  </xacro:property>

  <xacro:macro name="rover_amalia_chassis" params="Ox Oy Oz">
    <link name="rover_amalia_chassis">
      <pose>0 0 0 0 0 0</pose>
      <inertial>
        <pose>0.0216667 0 -0.0215556 0 -0 0</pose>
        <mass>9</mass>
        <inertia>
          <ixx>900.12</ixx>
          <ixy>-3.46945e-18</ixy>
          <ixz>-0.0139533</ixz>
          <iyy>900.352</iyy>
          <iyz>0</iyz>
          <izz>900.455</izz>
        </inertia>
      </inertial>
      <collision name="rover_amalia_chassis_collision">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <box>
            <size>0.492 0.334 0.1</size>
          </box>
        </geometry>
        <max_contacts>10</max_contacts>
      </collision>
      <collision name="rover_amalia_chassis_turret_base_collision">
        <xacro:insert_block name="rover_amalia_chassis_turret_base_pose"/>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_turret_base_size"/>
          </box>
        </geometry>
        <max_contacts>10</max_contacts>
      </collision>
      <visual name="rover_amalia_chassis_turret_base_visual">
        <xacro:insert_block name="rover_amalia_chassis_turret_base_pose"/>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_turret_base_size"/>
          </box>
        </geometry>
      </visual>
      <visual name="rover_amalia_chassis_body_visual">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_body_size"/>
          </box>
        </geometry>
      </visual>
      <visual name="rover_amalia_chassis_front_up_rangefinder_visual">
        <pose>0.246 0 -0.05 0 -0 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size"/>
          </box>
        </geometry>
      </visual>
      <visual name="rover_amalia_chassis_front_down_rangefinder_visual">
        <pose>${0.246-rover_amalia_chassis_rangefinder_size_y} 0 ${-0.05-rover_amalia_chassis_rangefinder_size_y} 0 1.57 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size"/>
          </box>
        </geometry>
      </visual>
      <visual name="rover_amalia_chassis_rear_up_rangefinder_visual">
        <pose>-0.246 0 -0.05 3.14159 0.00159265 3.14159</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size"/>
          </box>
        </geometry>
      </visual>
      <visual name="rover_amalia_chassis_rear_down_rangefinder_visual">
        <pose>${-0.246+rover_amalia_chassis_rangefinder_size_y} 0 ${-0.05-rover_amalia_chassis_rangefinder_size_y} 0 1.57 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size"/>
          </box>
        </geometry>
      </visual>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
  </xacro:macro>
</robot> 
