<?xml version="1.0" encoding="utf-8"?>
<robot name="rover_amalia_chassis" xmlns:xacro="http://www.w3.org/2001/XMLSchema-instance">
  <xacro:property name="pi" value="3.1415926" />

  <xacro:property name="rover_amalia_chassis_turret_base_size">
    <size>0.089 0.064 0.046</size>
  </xacro:property>

  <xacro:property name="rover_amalia_chassis_body_size">
    <!--<size>0.492 0.334 0.1</size>-->
    <size>${body_size_x} ${body_size_y} ${body_size_z}</size>
  </xacro:property>
  <xacro:property name="rover_amalia_chassis_rangefinder_size_y" value="0.01" />
  <xacro:property name="rover_amalia_chassis_rangefinder_size">
    <size>${rover_amalia_chassis_rangefinder_size_y} 0.03 ${rover_amalia_chassis_rangefinder_size_y}</size>
  </xacro:property>
  <xacro:property name="rover_amalia_chassis_turret_base_z" value="0.12" />
  <xacro:property name="rover_amalia_range_finder_z" value="${Oz-0.1}" />
  <xacro:macro name="rover_amalia_chassis" params="Ox Oy Oz body_size_x body_size_y body_size_z turret_base_x turret_base_y">
    <link name="rover_amalia_chassis">
      <pose>${Ox} ${Oy} ${Oz} 0 0 0</pose>
      <inertial>
        <pose>0.0216667 0 -0.0215556 0 -0 0</pose>
        <mass>15.6</mass>
        <inertia>
          <ixx>0.6385976</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.521</iyy>
          <iyz>0</iyz>
          <izz>0.318954</izz>
        </inertia>
      </inertial>
      <visual name="rover_amalia_chassis_body_visual">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_chassis/meshes/chassis.dae</uri>
          </mesh>
        </geometry>
        <material>
          <diffuse>0.4 0.4 0.4 1</diffuse>
          <specular>1 1 1 1</specular>
        </material>
      </visual>
      <collision name="rover_amalia_chassis_body_collision">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_body_size" />
          </box>
        </geometry>
        <max_contacts>10</max_contacts>
      </collision>
      <collision name="rover_amalia_chassis_turret_base_collision">
        <pose>${turret_base_x} ${turret_base_y} ${rover_amalia_chassis_turret_base_z} 0 0 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_turret_base_size" />
          </box>
        </geometry>
        <max_contacts>10</max_contacts>
      </collision>
      <visual name="rover_amalia_chassis_turret_base_visual">
        <pose>${turret_base_x} ${turret_base_y} ${rover_amalia_chassis_turret_base_z} 0 0 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_turret_base_size" />
          </box>
        </geometry>
        <material>
          <diffuse>0.4 0.4 0.4 1</diffuse>
          <specular>1 1 1 1</specular>
        </material>
      </visual>

      <visual name="rover_amalia_chassis_cpci">
        <pose>0 -0.08 0.1 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_chassis/meshes/cpci.dae</uri>
          </mesh>
        </geometry>
        <material>
          <diffuse>0.4 0.4 0.4 1</diffuse>
          <specular>1 1 1 1</specular>
        </material>
      </visual>

      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>

    <link name="rover_amalia_rangefinder_front">
      <visual name="rover_amalia_chassis_front_up_rangefinder_visual">
        <pose>0.246 0 ${rover_amalia_range_finder_z} 0 -0 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size" />
          </box>
        </geometry>
        <material>
          <ambient>0.1 0.1 0.1 1</ambient>
          <diffuse>0 0 0 1</diffuse>
        </material>
      </visual>

      <visual name="rover_amalia_chassis_front_down_rangefinder_visual">
        <pose>${0.246-rover_amalia_chassis_rangefinder_size_y} 0 ${rover_amalia_range_finder_z - rover_amalia_chassis_rangefinder_size_y} 0 1.57 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size" />
          </box>
        </geometry>
        <material>
          <ambient>0.1 0.1 0.1 1</ambient>
          <diffuse>0 0 0 1</diffuse>
        </material>
      </visual>
      <sensor name="range_front_down_ray" type="ray"> 
          <pose>0.25 0 ${rover_amalia_range_finder_z} 0 ${pi/2} 0</pose>
          <ray>
              <scan>
                  <horizontal>
                      <!-- could be just 1, but with 10 it is visualized in the gui-->
                      <samples>20</samples>
                      <resolution>1.0</resolution>
                      <min_angle>-0.02</min_angle>
                      <max_angle>0.02</max_angle>
                  </horizontal>
              </scan>
              <range>
                  <min>0.15</min>
                  <max>3</max>
              </range>
          </ray>
          <plugin name="range_finder_plugin_front" filename="libgazebo_ros_range_finder.so">
              <gaussianNoise>0.005</gaussianNoise>
              <alwaysOn>true</alwaysOn>
              <updateRate>20</updateRate>
              <topicName>/ADC/range_front_down</topicName>
              <frameName>rover_amalia_rangefinder_front</frameName>
          </plugin>
          <always_on>true</always_on>
          <update_rate>2.0</update_rate>
          <visualize>true</visualize>
      </sensor>
  </link>

  <link name="rover_amalia_rangefinder_rear">
      <visual name="rover_amalia_chassis_rear_up_rangefinder_visual">
        <pose>-0.246 0 ${rover_amalia_range_finder_z} 3.14159 0.00159265 3.14159</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size" />
          </box>
        </geometry>
        <material>
          <ambient>0.1 0.1 0.1 1</ambient>
          <diffuse>0 0 0 1</diffuse>
        </material>
      </visual>

      <visual name="rover_amalia_chassis_rear_down_rangefinder_visual">
        <pose>${-0.246+rover_amalia_chassis_rangefinder_size_y} 0 ${rover_amalia_range_finder_z - rover_amalia_chassis_rangefinder_size_y} 0 1.57 0</pose>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_chassis_rangefinder_size" />
          </box>
        </geometry>
        <material>
          <ambient>0.1 0.1 0.1 1</ambient>
          <diffuse>0 0 0 1</diffuse>
        </material>
      </visual>
      <sensor name="range_rear_down_ray" type="ray"> 
          <pose>${-0.248+rover_amalia_chassis_rangefinder_size_y} 0 ${rover_amalia_range_finder_z - rover_amalia_chassis_rangefinder_size_y} 0 1.57 0</pose>
          <ray>
              <scan>
                  <horizontal>
                      <!-- could be just 1, but with 10 it is visualized in the gui-->
                      <samples>20</samples>
                      <resolution>1.0</resolution>
                      <min_angle>-0.02</min_angle>
                      <max_angle>0.02</max_angle>
                  </horizontal>
              </scan>
              <range>
                  <min>0.15</min>
                  <max>3</max>
              </range>
          </ray>
          <plugin name="range_finder_plugin_rear" filename="libgazebo_ros_range_finder.so">
              <gaussianNoise>0.005</gaussianNoise>
              <alwaysOn>true</alwaysOn>
              <updateRate>20</updateRate>
              <topicName>/ADC/range_rear_down</topicName>
              <frameName>rover_amalia_rangefinder_rear</frameName>
          </plugin>
          <always_on>true</always_on>
          <update_rate>2.0</update_rate>
          <visualize>true</visualize>
      </sensor>
  </link>

  <joint name="rover_amalia_joint_chassis_rangefinder_front" type="revolute">
    <child>rover_amalia_rangefinder_front</child>
    <parent>rover_amalia_chassis</parent>
    <axis>
      <xyz>0 0 1</xyz>
      <limit>
        <lower>-1e-16</lower>
        <upper>1e-16</upper>
        <effort>1000</effort>
        <velocity>1000</velocity>
      </limit>
    </axis>
  </joint>
  <joint name="rover_amalia_joint_chassis_rangefinder_rear" type="revolute">
    <child>rover_amalia_rangefinder_rear</child>
    <parent>rover_amalia_chassis</parent>
    <axis>
      <xyz>0 0 1</xyz>
      <limit>
        <lower>-1e-16</lower>
        <upper>1e-16</upper>
        <effort>1000</effort>
        <velocity>1000</velocity>
      </limit>
    </axis>
  </joint>

  <plugin filename="libgazebo_ros_joint_state_publisher.so" name="rangefinder_rear_p">
    <robotNamespace></robotNamespace>
    <jointName>rover_amalia_joint_chassis_rangefinder_rear</jointName>
    <updateRate>10</updateRate>
  </plugin>
  <plugin filename="libgazebo_ros_joint_state_publisher.so" name="rangefinder_front_p">
    <robotNamespace></robotNamespace>
    <jointName>rover_amalia_joint_chassis_rangefinder_front</jointName>
    <updateRate>10</updateRate>
  </plugin>

  <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
    <alwaysOn>true</alwaysOn>       
    <bodyName>rover_amalia_chassis</bodyName>
    <topicName>imu_data</topicName>
    <serviceName>imu_service</serviceName>
    <gaussianNoise>0.0</gaussianNoise>
    <updateRate>10.0</updateRate> 
    <xyzOffset>0 0 0</xyzOffset>
    <rpyOffset>0 0 0</rpyOffset>
  </plugin>

  </xacro:macro>
</robot>
