<?xml version="1.0" ?>
<robot name="rover_amalia_turret" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="pi" value="3.1415926" />

  <xacro:property name="rover_amalia_turret_bar_radius" value="0.01"/>
  <xacro:property name="rover_amalia_turret_bar_pose">
    <pose>${Ox} ${Oy} ${Oz} 0 0 0</pose>
  </xacro:property>

  <xacro:property name="rover_amalia_turret_pan_base_height" value="0.02"/>
  <xacro:property name="rover_amalia_turret_pan_base_pose">
    <pose>${Ox} ${Oy} ${Oz+bar_height+rover_amalia_turret_pan_base_height/2} 0 0 0</pose>
  </xacro:property>
  <xacro:property name="rover_amalia_turret_pan_base_size">
      <size>0.04 0.06 ${rover_amalia_turret_pan_base_height} </size>
  </xacro:property>

  <xacro:property name="rover_amalia_turret_pan_tilt_height" value="0.04"/>
  <xacro:property name="rover_amalia_turret_tilt_base_pose">
    <pose>${Ox} ${Oy-0.01} ${Oz+bar_height+rover_amalia_turret_pan_base_height+rover_amalia_turret_pan_tilt_height/2} 0 0 0</pose>
  </xacro:property>
  <xacro:property name="rover_amalia_turret_tilt_base_size">
    <size>0.06 0.02 ${rover_amalia_turret_pan_tilt_height}</size>
  </xacro:property>

  <xacro:property name="rover_amalia_turret_robot_namespace" value="rover_amalia" />

  <xacro:macro name="rover_amalia_turret" params="Ox Oy Oz bar_height">
    <link name="rover_amalia_turret_bar">
      <xacro:insert_block name="rover_amalia_turret_bar_pose"/>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>0.5</mass>
        <inertia>
          <ixx>0.001</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.001</iyy>
          <iyz>0</iyz>
          <izz>0.001</izz>
        </inertia>
      </inertial>
      <collision name="rover_amalia_turret_bar_collision">
        <pose>0 0 ${bar_height/2} 0 0 0</pose>
        <geometry>
          <cylinder>
            <length>${bar_height}</length>
            <radius>${rover_amalia_turret_bar_radius}</radius>
          </cylinder>
        </geometry>
      </collision>
      <visual name="rover_amalia_turret_bar_visual">
        <pose>0 0 ${bar_height/2} 0 0 0</pose>
        <geometry>
          <cylinder>
            <length>${bar_height}</length>
            <radius>${rover_amalia_turret_bar_radius}</radius>
          </cylinder>
        </geometry>
      </visual>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
    <link name="rover_amalia_turret_pan_base">
      <xacro:insert_block name="rover_amalia_turret_pan_base_pose"/>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>1</mass>
        <inertia>
          <ixx>0.001</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.00100</iyy>
          <iyz>0</iyz>
          <izz>0.00100</izz>
        </inertia>
      </inertial>
      <visual name="rover_amalia_turret_pan_base_visual">
        <pose>-0.016 -0.02 0.015 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/pantilt_pan.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <velocity_decay>
        <linear>0</linear>
        <angular>0</angular>
      </velocity_decay>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
    <link name="rover_amalia_turret_tilt_base">
      <xacro:insert_block name="rover_amalia_turret_tilt_base_pose"/>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2</mass>
        <inertia>
          <ixx>0.00200001</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.00200001</iyy>
          <iyz>0</iyz>
          <izz>0.00200</izz>
        </inertia>
      </inertial>
      <collision name="rover_amalia_turret_tilt_base_collision">
        <pose>0 0 0 0 0 0</pose>
        <xacro:insert_block name="rover_amalia_turret_tilt_base_pose"/>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_turret_tilt_base_size"/>
          </box>
        </geometry>
        <max_contacts>10</max_contacts>
        <surface>
          <contact>
            <ode/>
          </contact>
          <bounce/>
          <friction>
            <ode/>
          </friction>
        </surface>
      </collision>
      <visual name="rover_amalia_turret_tilt_base_visual">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/pantilt_tilt.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <visual name="rover_amalia_turret_camera_set_visual">
        <pose>0 0 0.052 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/pantilt_payload.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <sensor name="depth_camera" type="depth">
        <pose>0 0 0 0 0 0</pose>
        <camera>
          <horizontal_fov>0.767944</horizontal_fov>
          <image>
            <width>176</width>
            <height>144</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.8</near>
            <far>9</far>
          </clip>
        </camera>
        <plugin filename="libgazebo_ros_depth_camera.so" name="depth_camera_plugin">
          <alwaysOn>1</alwaysOn>
          <robotNamespace>${rover_amalia_turret_robot_namespace}</robotNamespace>
          <updateRate>25.0</updateRate>
          <imageTopicName>image_raw</imageTopicName>
          <depthImageTopicName>depth_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>points</pointCloudTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <cameraName>depth_cam</cameraName>
          <frameName>/base_link</frameName>
          <pointCloudCutoff>0.001</pointCloudCutoff>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
        <always_on>true</always_on>
        <update_rate>25.0</update_rate>
      </sensor>
      <sensor name="camera" type="multicamera">
        <always_on>1</always_on>
        <update_rate>60</update_rate>
        <visualize>true</visualize>
        <camera name="left">
          <pose>0 0 0 0 0 0</pose>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>1280</width>
            <height>1024</height>
          </image>
          <clip>
            <near>0.4</near>
            <far>100</far>
          </clip>
        </camera>
        <camera name="right">
          <pose>0 0 0 0 0 0</pose>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>1280</width>
            <height>1024</height>
          </image>
          <clip>
            <near>0.4</near>
            <far>100</far>
          </clip>
        </camera>
        <plugin filename="libgazebo_ros_multicamera.so" name="stereo_camera_controller">
          <alwaysOn>true</alwaysOn>
          <updateRate>60.0</updateRate>
          <cameraName>camera</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>left_camera_optical_frame</frameName>
          <!--<rightFrameName>right_camera_optical_frame</rightFrameName>-->
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
      <velocity_decay>
        <linear>0</linear>
        <angular>0</angular>
      </velocity_decay>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
    <joint name="rover_amalia_turret_pan" type="revolute">
      <child>rover_amalia_turret_pan_base</child>
      <parent>rover_amalia_turret_bar</parent>
      <axis>
        <xyz>0 0 -1</xyz>
        <limit>
          <lower>-${pi}</lower>
          <upper>${pi}</upper>
        </limit>
        <dynamics/>
      </axis>
    </joint>
    <joint name="rover_amalia_turret_tilt" type="revolute">
      <child>rover_amalia_turret_tilt_base</child>
      <parent>rover_amalia_turret_pan_base</parent>
      <axis>
        <xyz>0 -1 0</xyz>
        <limit>
          <lower>${-pi*3/4}</lower>
          <upper>${pi*3/4}</upper>
        </limit>
        <dynamics/>
      </axis>
    </joint>
    <plugin filename="libgazebo_ros_joint_commander.so" name="joint_commander">
      <robotNamespace>${rover_amalia_turret_robot_namespace}</robotNamespace>
      <jointSet1>/ptu/cmd</jointSet1>
      <jointSet1Joint1>rover_amalia_turret_pan</jointSet1Joint1>
      <jointSet1Joint2>rover_amalia_turret_tilt</jointSet1Joint2>
    </plugin> 
  </xacro:macro>
</robot> 
