<?xml version="1.0" ?>
<robot name="rover_amalia_turret" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="pi" value="3.1415926" />

  <xacro:property name="rover_amalia_turret_bar_radius" value="0.01"/>
  <xacro:property name="rover_amalia_turret_bar_pose">
    <pose>${Ox} ${Oy} ${Oz} 0 0 0</pose>
  </xacro:property>

  <xacro:property name="rover_amalia_turret_tilt_base_height" value="0.02"/>
  <xacro:property name="pan_base_height" value="0.043"/>
  <xacro:property name="rover_amalia_turret_pan_base_pose">
    <pose>${Ox} ${Oy+0.015} ${Oz+pan_base_height+bar_height+rover_amalia_turret_tilt_base_height/2}-0.01 0 0 0</pose>
  </xacro:property>
  <xacro:property name="rover_amalia_turret_tilt_base_pose">
    <pose>${Ox} ${Oy+0.015} ${Oz+pan_base_height+bar_height+rover_amalia_turret_tilt_base_height/2} 0 0 0</pose>
  </xacro:property>
  <xacro:property name="rover_amalia_turret_tilt_base_size">
      <size>0.09 0.03 0.05 </size>
  </xacro:property>

  <xacro:property name="rover_amalia_turret_pan_tilt_height" value="0.04"/>
  <xacro:property name="rover_amalia_turret_tilt_hinge_pose">
    <pose>${Ox} ${Oy} ${Oz+pan_base_height+bar_height+rover_amalia_turret_tilt_base_height+rover_amalia_turret_pan_tilt_height/2} 0 0 0</pose>
  </xacro:property>
  <xacro:property name="rover_amalia_turret_tilt_hinge_size">
    <size>0.03 0.07 ${rover_amalia_turret_pan_tilt_height}</size>
  </xacro:property>

  <xacro:property name="rover_amalia_turret_robot_namespace" value="rover_amalia" />

  <xacro:macro name="rover_amalia_turret" params="Ox Oy Oz bar_height">
    <link name="rover_amalia_turret_bar_inertial_dummy">
      <xacro:insert_block name="rover_amalia_turret_bar_pose"/>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>0.78</mass>
        <inertia>
          <ixx>0.00000027555</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.00000027555</iyy>
          <iyz>0</iyz>
          <izz>0.00000027755</izz>
        </inertia>
      </inertial>
    </link>
    <link name="rover_amalia_turret_bar">
      <xacro:insert_block name="rover_amalia_turret_bar_pose"/>
      <collision name="rover_amalia_turret_bar_collision">
        <pose>0 0 ${bar_height/2} 0 0 0</pose>
        <geometry>
          <cylinder>
            <length>${bar_height}</length>
            <radius>${rover_amalia_turret_bar_radius}</radius>
          </cylinder>
        </geometry>
      </collision>
      <visual name="rover_amalia_turret_bar_visual">
        <pose>0 0 ${bar_height/2} 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/turret-and-pan-base.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
    <link name="rover_amalia_turret_pan_base_inertial_dummy">
      <xacro:insert_block name="rover_amalia_turret_pan_base_pose"/>
      <inertial>
        <pose>-0.00699 0.17952 0.02755 0 0 0</pose>
        <mass>0.22386</mass>
        <inertia>
          <ixx>0.00010575745</ixx>
          <ixy>0.00002524815</ixy>
          <ixz>0</ixz>
          <iyy>0.00100</iyy>
          <iyz>0</iyz>
          <izz>0.00021796864</izz>
        </inertia>
      </inertial>
    </link>
    <link name="rover_amalia_turret_tilt_base_inertial_dummy">
      <inertial>
        <pose>0.012 -0.21853 0.02754  0 0 0</pose>
        <pose>0 0 0 0 0 0</pose>
        <mass>0.02786</mass>
        <inertia>
          <ixx>0.00002247622</ixx>
          <ixy>0.</ixy>
          <ixz>0</ixz>
          <iyy>0.00001850151</iyy>
          <iyz>0</iyz>
          <izz>0.00000707185</izz>
        </inertia>
      </inertial>
    </link>
    <link name="rover_amalia_turret_tilt_base">
      <xacro:insert_block name="rover_amalia_turret_tilt_base_pose"/>
      <visual name="rover_amalia_turret_tilt_base_visual">
        <pose>-0.016 -0.02 0.015 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/pantilt_pan.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <collision name="rover_amalia_turret_tilt_base_collision">
        <pose>-0.02 0 0.01 0 0 0</pose>
        <xacro:insert_block name="rover_amalia_turret_tilt_hinge_pose"/>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_turret_tilt_base_size"/>
          </box>
        </geometry>
      </collision>
      <velocity_decay>
        <linear>0</linear>
        <angular>0</angular>
      </velocity_decay>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
    <link name="rover_amalia_turret_tilt_hinge">
      <xacro:insert_block name="rover_amalia_turret_tilt_hinge_pose"/>
      <collision name="rover_amalia_turret_tilt_hinge_collision">
        <pose>0 0 0 0 0 0</pose>
        <xacro:insert_block name="rover_amalia_turret_tilt_hinge_pose"/>
        <geometry>
          <box>
            <xacro:insert_block name="rover_amalia_turret_tilt_hinge_size"/>
          </box>
        </geometry>
        <max_contacts>10</max_contacts>
        <surface>
          <contact>
            <ode/>
          </contact>
          <bounce/>
          <friction>
            <ode/>
          </friction>
        </surface>
      </collision>
      <visual name="rover_amalia_turret_tilt_hinge_visual">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/pantilt_tilt.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <visual name="rover_amalia_turret_camera_set_visual">
        <pose>0 0 0.052 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>model://rover_amalia_turret/meshes/pantilt_payload.dae</uri>
          </mesh>
        </geometry>
      </visual>
      <sensor name="depth_camera" type="depth">
        <pose>0 0 0 0 0 0</pose>
        <camera>
          <horizontal_fov>0.767944</horizontal_fov>
          <image>
            <width>176</width>
            <height>144</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.8</near>
            <far>9</far>
          </clip>
        </camera>
        <plugin filename="libgazebo_ros_depth_camera.so" name="depth_camera_plugin">
          <alwaysOn>1</alwaysOn>
          <robotNamespace>${rover_amalia_turret_robot_namespace}</robotNamespace>
          <updateRate>25.0</updateRate>
          <imageTopicName>image_raw</imageTopicName>
          <depthImageTopicName>depth_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>points</pointCloudTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <cameraName>depth_cam</cameraName>
          <frameName>/base_link</frameName>
          <pointCloudCutoff>0.001</pointCloudCutoff>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
        <always_on>true</always_on>
        <update_rate>25.0</update_rate>
      </sensor>
      <sensor name="camera" type="multicamera">
        <always_on>1</always_on>
        <update_rate>60</update_rate>
        <visualize>true</visualize>
        <camera name="left">
          <pose>0 0 0 0 0 0</pose>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>1280</width>
            <height>1024</height>
          </image>
          <clip>
            <near>0.4</near>
            <far>100</far>
          </clip>
        </camera>
        <camera name="right">
          <pose>0 0 0 0 0 0</pose>
          <horizontal_fov>1.047</horizontal_fov>
          <image>
            <width>1280</width>
            <height>1024</height>
          </image>
          <clip>
            <near>0.4</near>
            <far>100</far>
          </clip>
        </camera>
        <plugin filename="libgazebo_ros_multicamera.so" name="stereo_camera_controller">
          <alwaysOn>true</alwaysOn>
          <updateRate>60.0</updateRate>
          <cameraName>stereo</cameraName>
          <imageTopicName>image_raw</imageTopicName>
          <cameraInfoTopicName>camera_info</cameraInfoTopicName>
          <frameName>left_camera_optical_frame</frameName>
          <rightFrameName>right_camera_optical_frame</rightFrameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
      <velocity_decay>
        <linear>0</linear>
        <angular>0</angular>
      </velocity_decay>
      <self_collide>0</self_collide>
      <kinematic>0</kinematic>
      <gravity>1</gravity>
    </link>
    <joint name="rover_amalia_turret_pan" type="revolute">
      <child>rover_amalia_turret_tilt_base</child>
      <parent>rover_amalia_turret_bar</parent>
      <axis>
        <xyz>0 0 -1</xyz>
        <limit>
          <lower>-${pi}</lower>
          <upper>${pi}</upper>
          <effort>1000</effort>
          <velocity>1000</velocity>
        </limit>
      </axis>
      <physics>
        <ode>
          <cfm>0.0001</cfm>
          <erp>0.2</erp>
        </ode>
      </physics>
    </joint>
    <joint name="rover_amalia_turret_tilt" type="revolute">
      <child>rover_amalia_turret_tilt_hinge</child>
      <parent>rover_amalia_turret_tilt_base</parent>
      <axis>
        <xyz>0 -1 0</xyz>
        <limit>
          <lower>${-pi*3/4}</lower>
          <upper>${pi*3/4}</upper>
          <effort>1000</effort>
          <velocity>1000</velocity>
        </limit>
      </axis>
      <physics>
        <ode>
          <cfm>0</cfm>
          <erp>0.2</erp>
        </ode>
      </physics>
    </joint>
    <plugin filename="libgazebo_ros_joint_commander.so" name="joint_commander">
      <robotNamespace>${rover_amalia_turret_robot_namespace}</robotNamespace>
      <jointSet1>/ptu/cmd</jointSet1>
      <jointSet1Joint1>rover_amalia_turret_pan</jointSet1Joint1>
      <jointSet1Joint2>rover_amalia_turret_tilt</jointSet1Joint2>
    </plugin> 
    <plugin filename="libgazebo_ros_joint_state_publisher.so" name="pan">
      <robotNamespace></robotNamespace>
      <jointName>rover_amalia_turret_pan</jointName>
      <updateRate>30</updateRate>
    </plugin>
    <plugin filename="libgazebo_ros_joint_state_publisher.so" name="tilt">
      <robotNamespace></robotNamespace>
      <jointName>rover_amalia_turret_tilt</jointName>
      <updateRate>30</updateRate>
    </plugin>
  </xacro:macro>
</robot> 
